"""Add vehicles and vehicles_users tables

Revision ID: 2e37c0074375
Revises: 7c38b3f35c6d
Create Date: 2025-12-17 05:33:51.982875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e37c0074375'
down_revision: Union[str, Sequence[str], None] = '7c38b3f35c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
