"""add_routes

Revision ID: 4fe570ac80bc
Revises: ec407f42f55e
Create Date: 2026-02-02 19:21:38.551684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe570ac80bc'
down_revision: Union[str, Sequence[str], None] = 'ec407f42f55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_routes_code')
    )
    op.create_index('idx_routes_created_by', 'routes', ['created_by'], unique=False)
    op.create_table('route_nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.BigInteger(), nullable=False),
    sa.Column('node_id', sa.BigInteger(), nullable=False),
    sa.Column('seq_no', sa.Integer(), nullable=False),
    sa.Column('distance_km_from_start', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('travel_minutes_from_start', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'node_id', name='uq_route_nodes_route_node'),
    sa.UniqueConstraint('route_id', 'seq_no', name='uq_route_nodes_route_seq')
    )
    op.create_index('idx_route_nodes_node', 'route_nodes', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_route_nodes_node', table_name='route_nodes')
    op.drop_table('route_nodes')
    op.drop_index('idx_routes_created_by', table_name='routes')
    op.drop_table('routes')
    # ### end Alembic commands ###
