"""add_nodes

Revision ID: ec407f42f55e
Revises: 96d01d448efa
Create Date: 2026-02-02 18:43:34.542977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec407f42f55e'
down_revision: Union[str, Sequence[str], None] = '96d01d448efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('type', sa.String(length=20), server_default=sa.text("'station'"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nodes_lat_lng', 'nodes', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_nodes_name', 'nodes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nodes_name', table_name='nodes')
    op.drop_index('idx_nodes_lat_lng', table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
